//
// Generated file, do not edit! Created by nedtool 4.6 from messages/DataMessage.msg.
//

#ifndef _DATAMESSAGE_M_H_
#define _DATAMESSAGE_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include <Coord.h>
// }}

/**
 * Class generated from <tt>messages/DataMessage.msg:22</tt> by nedtool.
 * <pre>
 * packet DataMessage
 * {
 *     Coord messageOriginPosition;
 *     double messageROI;
 *     simtime_t messageOriginTime;
 *     simtime_t messageTTL;
 *     int hops;
 * }
 * </pre>
 */
class DataMessage : public ::cPacket
{
  protected:
    Coord messageOriginPosition_var;
    double messageROI_var;
    simtime_t messageOriginTime_var;
    simtime_t messageTTL_var;
    int hops_var;

  private:
    void copy(const DataMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DataMessage&);

  public:
    DataMessage(const char *name=NULL, int kind=0);
    DataMessage(const DataMessage& other);
    virtual ~DataMessage();
    DataMessage& operator=(const DataMessage& other);
    virtual DataMessage *dup() const {return new DataMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual Coord& getMessageOriginPosition();
    virtual const Coord& getMessageOriginPosition() const {return const_cast<DataMessage*>(this)->getMessageOriginPosition();}
    virtual void setMessageOriginPosition(const Coord& messageOriginPosition);
    virtual double getMessageROI() const;
    virtual void setMessageROI(double messageROI);
    virtual simtime_t getMessageOriginTime() const;
    virtual void setMessageOriginTime(simtime_t messageOriginTime);
    virtual simtime_t getMessageTTL() const;
    virtual void setMessageTTL(simtime_t messageTTL);
    virtual int getHops() const;
    virtual void setHops(int hops);
};

inline void doPacking(cCommBuffer *b, DataMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DataMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DATAMESSAGE_M_H_

